#!/usr/bin/env python3
"""
Sync Catalog — One-Shot catalog.yaml Generator
===============================================
Scans all formal documents under .agents/modules/, .agents/units/,
and .agents/demands/, extracts their YAML frontmatter, and regenerates
catalog.yaml from scratch.

Usage:
    python .agents/tools/sync-catalog.py

This is idempotent — safe to run multiple times.
No PyYAML required; uses a minimal inline parser.
"""

from __future__ import annotations

import os
import re
import sys
from datetime import date
from pathlib import Path


def find_repo_root() -> Path:
    cwd = Path.cwd()
    for parent in [cwd, *cwd.parents]:
        if (parent / ".agents" / "catalog.yaml").exists():
            return parent
    return cwd


def extract_frontmatter(text: str) -> dict[str, str | list] | None:
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    yaml_text = text[3:end].strip()
    result: dict[str, str | list] = {}
    for line in yaml_text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, val = line.split(":", 1)
        key = key.strip()
        val = val.strip().strip('"\'')
        # Try to parse simple inline lists
        if val.startswith("[") and val.endswith("]"):
            val = [v.strip().strip('"\'') for v in val[1:-1].split(",") if v.strip()]
        result[key] = val
    return result


def scan_docs(agents_dir: Path) -> list[dict]:
    entries: list[dict] = []
    type_map = {
        "modules/": "module",
        "units/": "unit",
        "demands/": "demand",
    }

    for subdir, doc_type in type_map.items():
        dir_path = agents_dir / subdir
        if not dir_path.exists():
            continue
        for f in sorted(dir_path.iterdir()):
            if f.suffix != ".md":
                continue
            text = f.read_text(encoding="utf-8")
            fm = extract_frontmatter(text)
            if not fm or not fm.get("id"):
                continue
            entry = {
                "id": fm["id"],
                "title": fm.get("title", fm["id"]),
                "type": doc_type,
                "area": fm.get("area", ""),
                "status": fm.get("status", "active"),
                "path": str(f.relative_to(agents_dir.parent)).replace("\\", "/"),
            }
            for opt in ("related_units", "related_demands", "owner_module",
                        "source_paths", "entrypoints", "owners", "tags"):
                if opt in fm and fm[opt]:
                    entry[opt] = fm[opt]
            entries.append(entry)

    return entries


def build_catalog_text(areas: list[str], entries: list[dict]) -> str:
    lines = [
        "# .agents/catalog.yaml",
        "#",
        "# Auto-generated by .agents/tools/sync-catalog.py",
        "# Do NOT manually edit the documents list — run the sync script instead.",
        "#",
        "",
        f"version: 1",
        f"updated_at: {date.today().isoformat()}",
        "",
        "areas:",
    ]
    for a in areas:
        lines.append(f"  - {a}")
    lines.append("")
    lines.append("documents:")

    for e in entries:
        lines.append(f"  - id: {e['id']}")
        lines.append(f"    title: {e['title']}")
        lines.append(f"    type: {e['type']}")
        lines.append(f"    area: {e['area']}")
        lines.append(f"    status: {e['status']}")
        lines.append(f"    path: {e['path']}")
        for opt in ("related_units", "related_demands", "owner_module",
                    "source_paths", "entrypoints", "owners", "tags"):
            if opt in e and e[opt]:
                val = e[opt]
                if isinstance(val, list):
                    val = "[" + ", ".join(f'"{v}"' for v in val) + "]"
                lines.append(f"    {opt}: {val}")

    return "\n".join(lines) + "\n"


def extract_areas(catalog_path: Path) -> list[str]:
    """Preserve existing area definitions from current catalog.yaml."""
    if not catalog_path.exists():
        return []
    text = catalog_path.read_text(encoding="utf-8")
    match = re.search(r"^areas:\s*(.*?)(?=^\w+:|^# |\Z)", text, re.MULTILINE | re.DOTALL)
    if not match:
        return []
    return [
        line.strip("- ").strip()
        for line in match.group(1).splitlines()
        if line.strip().startswith("-") and not line.strip().startswith("#")
    ]


def main() -> int:
    repo_root = find_repo_root()
    agents_dir = repo_root / ".agents"
    catalog_path = agents_dir / "catalog.yaml"

    if not agents_dir.exists():
        print("ERROR: No .agents/ directory found.", file=sys.stderr)
        return 1

    areas = extract_areas(catalog_path)
    entries = scan_docs(agents_dir)

    text = build_catalog_text(areas, entries)
    catalog_path.write_text(text, encoding="utf-8")

    print(f"Synced {len(entries)} document(s) into catalog.yaml")
    if areas:
        print(f"Preserved {len(areas)} area(s): {', '.join(areas)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
